export const IMAGES = {
    
    //icons
    home : require('../assets/images/icons/home.png'),
    checkMark : require('../assets/images/icons/checkMark.png'),
    home2 : require('../assets/images/icons/home2.png'),
    wallet : require('../assets/images/icons/wallet.png'),
    wallet2 : require('../assets/images/icons/wallet2.png'),
    profitLoss : require('../assets/images/icons/profitloss.png'),
    history : require('../assets/images/icons/history.png'),
    referral : require('../assets/images/icons/referral.png'),
    profile : require('../assets/images/icons/profile.png'),
    deposit : require('../assets/images/icons/deposit.png'),
    deposit2 : require('../assets/images/icons/deposit2.png'),
    withdraw : require('../assets/images/icons/withdraw.png'),
    withdraw2 : require('../assets/images/icons/withdraw2.png'),
    transfer : require('../assets/images/icons/transfer.png'),
    edit : require('../assets/images/icons/edit.png'),
    verification : require('../assets/images/icons/verification.png'),
    settings : require('../assets/images/icons/settings.png'),
    support : require('../assets/images/icons/support.png'),
    language : require('../assets/images/icons/language.png'),
    history2 : require('../assets/images/icons/history2.png'),
    logout : require('../assets/images/icons/logout.png'),
    darkMode : require('../assets/images/icons/dark-mode.png'),
    mail : require('../assets/images/icons/mail.png'),
    phone : require('../assets/images/icons/phone.png'),
    lock : require('../assets/images/icons/lock.png'),
    scan : require('../assets/images/icons/scan.png'),
    copy : require('../assets/images/icons/copy.png'),
    grid : require('../assets/images/icons/grid.png'),
    instagram : require('../assets/images/icons/instagram.png'),
    whatsapp : require('../assets/images/icons/whatsapp.png'),
    facebook : require('../assets/images/icons/facebook.png'),
    twitter : require('../assets/images/icons/twitter.png'),
    dollor : require('../assets/images/icons/dollor.png'),
    sun : require('../assets/images/icons/sun.png'),
    checkmark : require('../assets/images/icons/checkMark.png'),
    crossbadge : require('../assets/images/icons/badge.png'),
    
    standardcard : require('../assets/images/standardcard.png'),
    premiumcard: require('../assets/images/premiumcard.png'),
    elitecard: require('../assets/images/elitecard.png'),

    logo : require('../assets/images/logo.png'),
    onBoarding1 : require('../assets/images/onboarding/pic1.png'),
    onBoarding2 : require('../assets/images/onboarding/pic2.png'),
    onBoarding3 : require('../assets/images/onboarding/pic3.png'),
    pattern1 : require('../assets/images/pattern/pattern1.png'),
    pattern2 : require('../assets/images/pattern/pattern2.png'),
    pattern3 : require('../assets/images/pattern/pattern3.png'),
    profilePic : require('../assets/images/profilePic.png'),
    visa : require('../assets/images/visa.png'),
    qrcode : require('../assets/images/qrcode.png'),
    dropdown : require('../assets/images/icons/dropdown.png'),
    addwallet : require('../assets/images/icons/addwallet.png'),

    card1 : require('../assets/images/pattern/card/card1.png'),

    btc : require('../assets/images/coins/btc.png'),
    eth : require('../assets/images/coins/eth.png'),
    sol : require('../assets/images/coins/sol.png'),
    xrp : require('../assets/images/coins/xrp.png'),
    bnb : require('../assets/images/coins/bnb.png'),
    usdt : require('../assets/images/coins/usdt.png'),
    usdc : require('../assets/images/coins/usdc.png'),
    aiat : require('../assets/images/coins/aiat.png'),
    cco2 : require('../assets/images/coins/cco2.png'),
    ltc : require('../assets/images/coins/ltc.png'),
    trx : require('../assets/images/coins/trx.png'),
    fil : require('../assets/images/coins/fil.png'),
    link : require('../assets/images/coins/link.png'),
    dot : require('../assets/images/coins/dot.png'),
    doge : require('../assets/images/coins/doge.png'),
    shib : require('../assets/images/coins/shib.png'),
    ada : require('../assets/images/coins/ada.png'),
    avax : require('../assets/images/coins/avax.png'),
    uni : require('../assets/images/coins/uni.png'),
    arb : require('../assets/images/coins/arb.png'),
    pepe : require('../assets/images/coins/pepe.png'),
    bch : require('../assets/images/coins/bch.png'),
    defaultTokenIcon : require('../assets/images/coins/aiat.png'),

}